apiVersion: apps/v1
kind: Deployment
metadata:
  name: expirationservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expirationservice
  template:
    metadata:
      labels:
        app: expirationservice
    spec:
      containers:
        - name: expirationservice
          image: kolabayo360/trollyexpiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-serv:4222"
            - name: NATS_CLUSTER_ID
              value: trolly
            - name: REDIS_HOST
              value: expiration-redis-srv
