apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersservice
  template:
    metadata:
      labels:
        app: ordersservice
    spec:
      containers:
        - name: ordersservice
          image: kolabayo360/trollyorders
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-serv:4222"
            - name: NATS_CLUSTER_ID
              value: trolly
            - name: MONGO_URI
              value: "mongodb://orders-mongo-srv:27017/ordersservicedb"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ordersservice-serv
spec:
  selector:
    app: ordersservice
  ports:
    - name: ordersservice
      protocol: TCP
      port: 3000
      targetPort: 3000
