apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentsservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentsservice
  template:
    metadata:
      labels:
        app: paymentsservice
    spec:
      containers:
        - name: paymentsservice
          image: kolabayo360/trollypayments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-serv:4222"
            - name: NATS_CLUSTER_ID
              value: trolly
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/paymentsservicedb"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: paymentsservice-serv
spec:
  selector:
    app: paymentsservice
  ports:
    - name: paymentsservice
      protocol: TCP
      port: 3000
      targetPort: 3000
